### ISSUE TITLE
node-red integration

### ISSUE THREAD

**Issue by jk2020** [MariusRumpf/max31865#1]
Great module and works like a charm!
It took my a while to realize that it is hard coded to use pin 24 - GPIO8 - CE0
GPIO Port as a variable would be great

What I really miss is additional code to provide a node for node-red.
There is a similar module "node-red-contrib-sensor-ds18b20" available for node-red which is a good example howto create additional files sensor.js and sensor.html needed to enhance the max31865 module for node-red node support.

**Comment by MariusRumpf** [comment]
The gpio pin is not hard coded, the first and second parameter of the constructor are describing the `/dev` interface to use: `new MAX31865(0, 0); // For /dev/spidev0.0`. The device you use might have different spi interfaces exposed as `/dev/spidev0.1` or similar. According to that you can set this parameters. The spi device exposed by your device is internally associated to a specific GPIO pin. Not every GPIO pin supports SPI. 
I agree with you that a setup description for the raspberry pi would be useful for example, created #2.

**Comment by MariusRumpf** [comment]
There seems to be a node-red package from MalvinRook
https://www.npmjs.com/package/node-red-contrib-pi-max31865
