### ISSUE TITLE
Problem with Adafruit Breakout board 

### ISSUE THREAD

**Issue by VaderMester** [MariusRumpf/max31865#5]
Hi Mearius,

The library seems to be working software wise, but somehow strange thing happen on the MISO line. It seems that on every clock edge, there is a very short - 100ns- spike on the MISO line. The timing of events seem OK though, as the read and write functions are called.
Posted to fivdi's repo as well, please read. Did you experience such behavour with Max31865s? (Using Adafruit board)
https://github.com/fivdi/spi-device/issues/14

**Comment by MariusRumpf** [comment]
I saw that you found the problem was caused by using this library (and the underlying `spi-device`) together with `node-rpio`. 
Thanks for your problem search, I will close this issue then.
